[versions]
android-build = "7.1.3"
kotlin = "1.6.10"
hilt = "2.41"
sqldelight = "1.5.3"
protobuf = "3.19.4"
androidx-compose = "1.1.1"
androidx-lifecycle = "2.4.1"
accompnist = "0.23.1"
ktor = "1.6.8"
compose-destinations = "1.5.0-beta"
coroutines = { strictly = "1.6.0-native-mt" }

[libraries]
plugin-android = { module = "com.android.tools.build:gradle", version.ref = "android-build" }
plugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
plugin-kotlinx-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }
plugin-hilt = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
plugin-protobuf = "com.google.protobuf:protobuf-gradle-plugin:0.8.18"
plugin-sqldelight = { module = "com.squareup.sqldelight:gradle-plugin", version.ref = "sqldelight" }
plugin-gradle-version = "com.github.ben-manes:gradle-versions-plugin:0.39.0"
plugin-ksp = "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:1.6.10-1.0.4"
plugin-ktlint = "org.jlleitschuh.gradle:ktlint-gradle:10.2.1"

androidx-core = "androidx.core:core-ktx:1.7.0"
androidx-compat = "androidx.appcompat:appcompat:1.4.1"
androidx-datastore = "androidx.datastore:datastore:1.0.0"
androidx-browser = "androidx.browser:browser:1.4.0"

androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }

androidx-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "androidx-compose" }
androidx-compose-material = { module = "androidx.compose.material:material", version.ref = "androidx-compose" }
androidx-compose-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "androidx-compose" }
androidx-compose-nvaigation = "androidx.navigation:navigation-compose:2.4.1"
androidx-compose-nvaigation-hilt = "androidx.hilt:hilt-navigation-compose:1.0.0"

accompanist-flowlayout = { module = "com.google.accompanist:accompanist-flowlayout", version.ref = "accompnist" }
accompanist-swiperefresh = { module = "com.google.accompanist:accompanist-swiperefresh", version.ref = "accompnist" }
accompanist-navigation-animation = { module = "com.google.accompanist:accompanist-navigation-animation", version.ref = "accompnist" }

compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:animations-core", version.ref = "compose-destinations" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations" }

coil-compose = "io.coil-kt:coil-compose:1.4.0"

material = "com.google.android.material:material:1.5.0"

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

ktor-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-ios = { module = "io.ktor:ktor-client-ios", version.ref = "ktor" }
ktor-serialization = { module = "io.ktor:ktor-client-serialization", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }

kotlinx-serialization = "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }

protobuf-java = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-protoc = { module = "com.google.protobuf:protoc", version.ref = "protobuf" }

sqldelight-runtime = { module = "com.squareup.sqldelight:runtime", version.ref = "sqldelight" }
sqldelight-android = { module = "com.squareup.sqldelight:android-driver", version.ref = "sqldelight" }
sqldelight-native = { module = "com.squareup.sqldelight:native-driver", version.ref = "sqldelight" }

napier = "io.github.aakira:napier:2.4.0"

# debug
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "androidx-compose" }

# test
junit = "junit:junit:4.13.2"
androidx-junit = "androidx.test.ext:junit:1.1.3"
espresso = "androidx.test.espresso:espresso-core:3.4.0"

kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

[bundles]
plugins = [
    "plugin-android",
    "plugin-kotlin",
    "plugin-kotlinx-serialization",
    "plugin-hilt",
    "plugin-protobuf",
    "plugin-sqldelight",
    "plugin-gradle-version",
    "plugin-ksp",
    "plugin-ktlint"
]

androidx-compose = [
    "androidx-compose-ui",
    "androidx-compose-material",
    "androidx-compose-preview",
    "androidx-compose-nvaigation",
    "androidx-compose-nvaigation-hilt",
    "accompanist-flowlayout",
    "accompanist-swiperefresh",
    "accompanist-navigation-animation",
    "coil-compose",
    "compose-destinations-core"
]

