output-reports:
  exclude:
    - 'TxtOutputReport'
    - 'XmlOutputReport'
    - 'HtmlOutputReport'
    - 'MdOutputReport'
complexity:
  LongParameterList:
    functionThreshold: 100
    ignoreDefaultParameters: true
  LongMethod:
    threshold: 120
naming:
  PackageNaming:
    active: false
  FunctionNaming:
    ignoreAnnotated: ['Composable']
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'
style:
  MagicNumber:
    ignoreAnnotated: ['Preview', 'DagashiPreview']
    ignorePropertyDeclaration: true
  UnusedPrivateMember:
    ignoreAnnotated: ['Preview', 'DagashiPreview']
exceptions:
  TooGenericExceptionCaught:
    active: false
  TooGenericExceptionThrown:
    active: false
formatting:
  PackageName:
    active: false
  Filename:
    active: false
  MaximumLineLength:
    maxLineLength: 256
