name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
#  build:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.10.0
#        with:
#          access_token: ${{ github.token }}
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#          cache: gradle
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@v1
#      - name: Build app
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: :androidApp:app:assembleDebug

#  test:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Cancel Previous Runs
#        uses: styfle/cancel-workflow-action@0.10.0
#        with:
#          access_token: ${{ github.token }}
#      - uses: actions/checkout@v3
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'adopt'
#          cache: gradle
#      - name: Validate Gradle wrapper
#        uses: gradle/wrapper-validation-action@v1
#      - name: Run unit test
#        uses: gradle/gradle-build-action@v2
#        with:
#          arguments: testCI

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
#      - name: Setup Ruby
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '3.1'
#      - name: Install danger
#        run: bundle install
      - name: Run lint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: clean androidApp:app:lintDebug
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: androidApp/app/build/reports/lint-results-debug.sarif
#      - name: Run Dnager
#        run: bundle exec danger
#        env:
#          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.10.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
#      - name: Setup Ruby
#        uses: actions/setup-ruby@v1
#        with:
#          ruby-version: '3.1'
#      - name: Install danger
#        run: bundle install
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install @microsoft/sarif-multitool
        run: npm i -g @microsoft/sarif-multitool
      - name: Run ktlint
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ktlintCheck mergeKtlint
      - name: Upload sarif
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: build/mergedKtlintReport.sarif
#      - name: Run Dnager
#        run: bundle exec danger
#        env:
#          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
